### ISSUE TITLE
Sonar Deprecation

### ISSUE THREAD

**Issue by reitzmichnicht** [sbaudoin/sonar-yaml#32]
With Sonar 7.9 LTS and Yaml Plugin 1.4.3 I get the following deprecation warning:

> Metric 'comment_lines_data' is deprecated. Provided value is ignored.

This seems to come from LineCounter class using CoreMetrics.COMMENT_LINES_DATA_KEY.

**Comment by sbaudoin** [comment]
Hi,

Thanks for reporting. Yes, I know about that. If I'm not wrong, you meet this issue as of SQ 7.3. I keep this metrics however because the plugin is compatible with SQ 6 and it is relevant for this version.

The API doc says that "measures are no longer sent within analysis reports" so I have to fix that in a next release but to be honest the SonarQube documentation is pretty poor and has not helped me so far find the proper to replace the way I calculate measures in my plugin. If you have some inputs on this, I'll be very happy.

Regards

**Comment by sbaudoin** [comment]
According to https://community.sonarsource.com/t/as-of-7-3-what-is-the-proper-way-to-calculate-the-comment-lines-data-measure/11712/2, my code is already doing the right thing (meaning, using COMMENT_LINES), so the warning can be safely ignored.

**Comment by reitzmichnicht** [comment]
Then please send this metric depending on Sonar version. See this doc:
http://javadocs.sonarsource.org/7.9/apidocs/org/sonar/api/SonarRuntime.html

**Comment by sbaudoin** [comment]
Sorry but what is wrong with this warning? As far as I know it appears in the scanner output so you can just ignore it?

**Comment by reitzmichnicht** [comment]
We have a zero warning policy, so we try to avoid getting warnings if possible.     Normally a warning should indicate that something might be wrong which is not the case here.

**Comment by sbaudoin** [comment]
OK, it makes sense, I'll do that. Implementing the checks for such a policy could take some times, I hope you are not in a rush.
