### ISSUE TITLE
Still reads .yaml files even if remove .yaml file extension

### ISSUE THREAD

**Issue by mieliespoor** [sbaudoin/sonar-yaml#67]
When removing the .yaml file extension from the list of file suffixes, this plugin still reads the files in the source location. 

We have another extension in Sonarqube that should read files with the .yaml extension so we need this plugin to not also read the file when we tell it to not do so.

**Comment by sbaudoin** [comment]
Hi. I rely on the scanner to get the files to be scanned. I may enforce the extension check but as I understand it the plugin is not supposed to do so. So I'd check if there are some configuration conflicts somewhere. Still digging, though.

**Comment by mieliespoor** [comment]
I forgot about this issue. We ended up being able to get the owners of the other plugin to fix a few things on their end as they made wide assumptions. I don't think this is still an issue.

**Comment by sbaudoin** [comment]
That's sort of a workaround. Why not. After a bit of research, I couldn't find in the PHP or HTML plugins some code that would explicitly filter out the files depending on suffixes: they seem to rely on the standard SQ mechanism. My impression is that, when running multiple plugins at once, the runner put together  all files filtered in by the different plugins it runs. I would need some more tests to confirm that. But if I'm right I can't say if this is the expected behavior.

I keep the issue open for a while, hopping I manage to search a bit deeper.

**Comment by sbaudoin** [comment]
I'm adding a test to exclude files whose suffix does match those configured for the plugin
